test:
  image: ubuntu
  before_script:
    - apt-get update -qy
    # Depending on Ubuntu version, one of the following should succeed in
    # installing the add-apt-repository command.
    - apt-get install software-properties-common -y || true
    - apt-get install python-software-properties -y || true
    - add-apt-repository ppa:ubuntu-toolchain-r/test -y
    # Update again now that we have new respoitories.
    - apt-get update -qy
    - apt-get install -y python3-minimal python3-pip
    - apt-get install -y g++-5 gcc-5 lcov cmake
    - python --version
    - pip3 install conan
    - pip3 install jinja2
    - ./fips set config linux-make-debug
    - ./fips gen
    - ./fips build
  script:
    - ./fips run test_runner
