test:
  image: ubuntu:zesty
  cache:
    paths:
    - cache
    - conan-cache
  before_script:
    - apt-get update -qy
    - apt-get install -y python3 python3-pip g++-6 gcc-6 lcov cmake git curl
    - export XDG_CACHE_HOME=$CI_PROJECT_DIR/cache
    - pip3 install virtualenv
    - virtualenv --python=python3 python-env
    - source python-env/bin/activate
    - python --version
    - pip install conan jinja2 gcovr pytest websocket-client
    - export CC=`which gcc-6`
    - export CXX=`which g++-6`
    - export CONAN_USER_HOME=`pwd`/conan-cache
    - ./fips set config linux-make-debug
    - ./fips gen
  script:
    - ./fips make unit_test_coverage
    - ./fips make integration_tests

codeclimate:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate init
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > codeclimate.json
  artifacts:
    paths: [codeclimate.json]
