sudo: required
dist: trusty

language: python
python:
  - 3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - lcov
      - cmake
      - git
      - curl
      - binutils-2.26

before_script:
  - export PATH=/usr/lib/binutils-2.26/bin:${PATH}
  - export CC=`which gcc-5`
  - export CXX=`which g++-5`
  - sudo setup.sh
  - ./fips set config linux-make-debug
  - ./fips gen

script:
  - python python/generate_config.py $CRADLE_THINKNODE_API_TOKEN
  - ./fips make unit_test_coverage
  - ./fips make integration_tests
