sudo: required
dist: trusty

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update -qy
  - sudo apt-get install -y python3.6 g++-6 gcc-6 lcov cmake git curl
  - curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
  - export XDG_CACHE_HOME=$TRAVIS_BUILD_DIR/cache
  - sudo python3.6 -m pip install virtualenv
  - python3.6 -m virtualenv --python=python3.6 python-env
  - source python-env/bin/activate
  - python --version
  - pip install conan jinja2 gcovr pytest websocket-client
  - export CC=`which gcc-6`
  - export CXX=`which g++-6`
  - export CONAN_USER_HOME=`pwd`/conan-cache
  - ./fips set config linux-make-debug
  - ./fips gen

script:
  - python python/generate_config.py $CRADLE_THINKNODE_API_TOKEN
  - ./fips make unit_test_coverage
  - ./fips make integration_tests
