language: python

python:
  - 3.6

os:
  - linux

# Ubuntu 14.04 Trusty support
sudo: false
dist: trusty

addons:
  apt:
    sources:
      # Add PPAs with more up-to-date toolchains
      - ubuntu-toolchain-r-test
      - git-core
    packages:
      - cmake
      - g++-5
      - gcc-5
      - lcov

before_install:
  - pip install conan
  - pip install jinja2

install:
  - export CXX="g++-5" CC="gcc-5"
  - ./fips set config linux-make-debug
  - ./fips gen
  - ./fips build

script:
  - ./fips run test_runner

after_success:
  - bash <(curl -s https://codecov.io/bash)
