sudo: false
dist: trusty

language: python
python:
  - 3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      - lcov
      - cmake
      - git
      - curl

before_script:
  - export XDG_CACHE_HOME=$TRAVIS_BUILD_DIR/cache
  - python --version
  - pip install conan jinja2 gcovr pytest websocket-client
  - export CC=`which gcc-6`
  - export CXX=`which g++-6`
  - export CONAN_USER_HOME=`pwd`/conan-cache
  - ./fips set config linux-make-debug
  - ./fips gen

script:
  - python python/generate_config.py $CRADLE_THINKNODE_API_TOKEN
  - ./fips make unit_test_coverage
  - ./fips make integration_tests
